spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.100.132:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hlinakrb0926
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
file.uploadDic: G:/root/usr/upload/firstPictures/
logging:
  level:
    root: info
    com.itomelet: debug
  file:
    name: log/blog-dev.log



