spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.100.132:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hlinakrb0926
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    root: warn
    com.itomelet: info
  file:
    name: log/blog-pro.log


